In [2]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [3]:
#Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

# Series is like a column, a DataFrame is the whole table.

In [4]:
my_data = randn(4,3) # rows and columns
my_rows = ["A","B","C","D"] # row head 
my_columns = ["Senuy", "Selus","Rebu"] #column head

In [8]:
#create DataFrame.
df = pd.DataFrame(my_data, my_rows, my_columns)

In [7]:
df

      Senuy     Selus      Rebu
A  0.753973  0.367229  0.479601
B  2.251842  1.333780 -0.553572
C -0.071995 -0.539321 -1.355535
D -0.484647 -1.054335  0.495528

In [9]:
#import or read csv files
my_df2 = pd.read_csv("coursera_course_dataset_v3.csv")
my_df2

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,"700,909",Google Cloud Fundamentals: Core Infrastructure...,20K,Beginner,Professional Certificate,3 - 6 Months
1,1,Google Data Analytics,Google,"Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,"229,865",Prepare for a new career in the high-growth fi...,137K,Beginner,Professional Certificate,3 - 6 Months
2,3,Google Project Management:,Google,"Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,"29,702",Prepare-se para uma nova carreira no campo de ...,100K,Beginner,Professional Certificate,3 - 6 Months
3,4,IBM Data Science,IBM,"Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,"239,622",Prepare for a career in the high-growth field ...,120K,Beginner,Professional Certificate,3 - 6 Months
4,5,Google Digital Marketing & E-commerce,Google,"Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,"384,238",This course is the eighth course in the Google...,23K,Beginner,Professional Certificate,3 - 6 Months
...,...,...,...,...,...,...,...,...,...,...,...,...
618,624,Google Workspace Security,Google Cloud,"Security Engineering, Security Strategy, Soft...",4.7,NaN,NaN,NaN,762,Beginner,Course,1 - 4 Weeks
619,625,Cybersecurity for Tech Professionals,Campus BBVA,"Computer Security Incident Management, System...",4.7,NaN,NaN,NaN,106,Intermediate,Course,1 - 3 Months
620,626,Cybersecurity in the Cloud,University of Minnesota,"Security Engineering, System Security, Networ...",4.3,NaN,NaN,NaN,127,Beginner,Specialization,3 - 6 Months
621,627,Applied Cryptography,University of Colorado System,"Cryptography, Security Engineering, Algorithm...",4.5,NaN,NaN,NaN,744,Intermediate,Specialization,3 - 6 Months
622,628,Python for Active Defense,Infosec,"Computer Programming, Python Programming",4.3,NaN,NaN,NaN,37,Intermediate,Course,1 - 4 Weeks

In [10]:
# pull out rows 0
my_df2.loc[0]

Unnamed: 0                                                                  0
Title                                                    Google Cybersecurity
Organization                                                           Google
Skills                       Network Security, Python Programming, Linux, ...
Ratings                                                                   4.8
course_url                  https://www.coursera.org/professional-certific...
course_students_enrolled                                              700,909
course_description          Google Cloud Fundamentals: Core Infrastructure...
Review Count                                                              20K
Difficulty                                                           Beginner
Type                                                 Professional Certificate
Duration                                                         3 - 6 Months
Name: 0, dtype: object

In [11]:
# pull out rows multiple rows ex: row 0 and 1
my_df2.loc[[0,1]]

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,"700,909",Google Cloud Fundamentals: Core Infrastructure...,20K,Beginner,Professional Certificate,3 - 6 Months
1,1,Google Data Analytics,Google,"Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,"229,865",Prepare for a new career in the high-growth fi...,137K,Beginner,Professional Certificate,3 - 6 Months

In [14]:
# pull out rows multiple rows ex: row 0 , 3 and 5:- add as much row number you want to see
my_df2.loc[[0,3,5]]

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,"700,909",Google Cloud Fundamentals: Core Infrastructure...,20K,Beginner,Professional Certificate,3 - 6 Months
3,4,IBM Data Science,IBM,"Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,"239,622",Prepare for a career in the high-growth field ...,120K,Beginner,Professional Certificate,3 - 6 Months
5,6,IBM Data Analyst,IBM,"Python Programming, Microsoft Excel, Data Vis...",4.6,https://www.coursera.org/professional-certific...,"173,574",Prepare for a career in the high-growth field ...,73K,Beginner,Professional Certificate,3 - 6 Months

In [15]:
# pull first 5 rows
my_df2.head()

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,"700,909",Google Cloud Fundamentals: Core Infrastructure...,20K,Beginner,Professional Certificate,3 - 6 Months
1,1,Google Data Analytics,Google,"Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,"229,865",Prepare for a new career in the high-growth fi...,137K,Beginner,Professional Certificate,3 - 6 Months
2,3,Google Project Management:,Google,"Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,"29,702",Prepare-se para uma nova carreira no campo de ...,100K,Beginner,Professional Certificate,3 - 6 Months
3,4,IBM Data Science,IBM,"Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,"239,622",Prepare for a career in the high-growth field ...,120K,Beginner,Professional Certificate,3 - 6 Months
4,5,Google Digital Marketing & E-commerce,Google,"Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,"384,238",This course is the eighth course in the Google...,23K,Beginner,Professional Certificate,3 - 6 Months

In [16]:
# pull certian numbers of rows: ex 9 rows
my_df2.head(9)

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,"700,909",Google Cloud Fundamentals: Core Infrastructure...,20K,Beginner,Professional Certificate,3 - 6 Months
1,1,Google Data Analytics,Google,"Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,"229,865",Prepare for a new career in the high-growth fi...,137K,Beginner,Professional Certificate,3 - 6 Months
2,3,Google Project Management:,Google,"Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,"29,702",Prepare-se para uma nova carreira no campo de ...,100K,Beginner,Professional Certificate,3 - 6 Months
3,4,IBM Data Science,IBM,"Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,"239,622",Prepare for a career in the high-growth field ...,120K,Beginner,Professional Certificate,3 - 6 Months
4,5,Google Digital Marketing & E-commerce,Google,"Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,"384,238",This course is the eighth course in the Google...,23K,Beginner,Professional Certificate,3 - 6 Months
5,6,IBM Data Analyst,IBM,"Python Programming, Microsoft Excel, Data Vis...",4.6,https://www.coursera.org/professional-certific...,"173,574",Prepare for a career in the high-growth field ...,73K,Beginner,Professional Certificate,3 - 6 Months
6,7,Google IT Support,Google,"Computer Networking, Network Architecture, Ne...",4.8,https://www.coursera.org/professional-certific...,"634,525","This beginner-level, six-course certificate, d...",183K,Beginner,Professional Certificate,3 - 6 Months
7,9,Machine Learning,Multiple educators,"Machine Learning, Machine Learning Algorithms...",4.9,https://www.coursera.org/specializations/machi...,"201,871",This Specialization from leading researchers a...,19K,Beginner,Specialization,1 - 3 Months
8,11,Google UX Design,Google,"User Experience, User Experience Design, User...",4.8,https://www.coursera.org/professional-certific...,"1,297,487",Prepare for a new career in the high-growth fi...,75K,Beginner,Professional Certificate,3 - 6 Months

In [17]:
# pull last 5 rows
my_df2.tail()

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
618,624,Google Workspace Security,Google Cloud,"Security Engineering, Security Strategy, Soft...",4.7,NaN,NaN,NaN,762,Beginner,Course,1 - 4 Weeks
619,625,Cybersecurity for Tech Professionals,Campus BBVA,"Computer Security Incident Management, System...",4.7,NaN,NaN,NaN,106,Intermediate,Course,1 - 3 Months
620,626,Cybersecurity in the Cloud,University of Minnesota,"Security Engineering, System Security, Networ...",4.3,NaN,NaN,NaN,127,Beginner,Specialization,3 - 6 Months
621,627,Applied Cryptography,University of Colorado System,"Cryptography, Security Engineering, Algorithm...",4.5,NaN,NaN,NaN,744,Intermediate,Specialization,3 - 6 Months
622,628,Python for Active Defense,Infosec,"Computer Programming, Python Programming",4.3,NaN,NaN,NaN,37,Intermediate,Course,1 - 4 Weeks

In [18]:
# pull certian numbers of rows: ex 6 rows from last 
my_df2.tail(6)

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
617,623,Security Principles,ISC2,Leadership and Management,4.7,https://www.coursera.org/learn/-security-princ...,"10,313",Welcome to course 1 of 5 of this Specializatio...,245,Beginner,Course,1 - 3 Months
618,624,Google Workspace Security,Google Cloud,"Security Engineering, Security Strategy, Soft...",4.7,NaN,NaN,NaN,762,Beginner,Course,1 - 4 Weeks
619,625,Cybersecurity for Tech Professionals,Campus BBVA,"Computer Security Incident Management, System...",4.7,NaN,NaN,NaN,106,Intermediate,Course,1 - 3 Months
620,626,Cybersecurity in the Cloud,University of Minnesota,"Security Engineering, System Security, Networ...",4.3,NaN,NaN,NaN,127,Beginner,Specialization,3 - 6 Months
621,627,Applied Cryptography,University of Colorado System,"Cryptography, Security Engineering, Algorithm...",4.5,NaN,NaN,NaN,744,Intermediate,Specialization,3 - 6 Months
622,628,Python for Active Defense,Infosec,"Computer Programming, Python Programming",4.3,NaN,NaN,NaN,37,Intermediate,Course,1 - 4 Weeks

In [19]:
# grab info about dataframe
my_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                623 non-null    int64
 1   Title                     623 non-null    object
 2   Organization              623 non-null    object
 3   Skills                    623 non-null    object
 4   Ratings                   623 non-null    float64
 5   course_url                403 non-null    object
 6   course_students_enrolled  387 non-null    object
 7   course_description        402 non-null    object
 8   Review Count              623 non-null    object
 9   Difficulty                623 non-null    object
 10  Type                      623 non-null    object
 11  Duration                  623 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 58.5+ KB

In [20]:
#grab the shape of each column
my_df2.shape

(623, 12)

In [21]:
#get dimwnssion of dataframe
my_df2.ndim

2

In [22]:
#get column datatype
my_df2.dtypes

Unnamed: 0                    int64
Title                        object
Organization                 object
Skills                       object
Ratings                     float64
course_url                   object
course_students_enrolled     object
course_description           object
Review Count                 object
Difficulty                   object
Type                         object
Duration                     object
dtype: object

In [23]:
#get statisctics about the data
my_df2.describe()

       Unnamed: 0     Ratings
count  623.000000  623.000000
mean   316.590690    4.640931
std    180.579572    0.195883
min      0.000000    2.800000
25%    161.500000    4.600000
50%    317.000000    4.700000
75%    472.500000    4.800000
max    628.000000    5.000000

In [24]:
#describe specific column
my_df2["Organization"].describe()

count     623
unique    115
top       IBM
freq       69
Name: Organization, dtype: object

In [26]:
#select specific column using brackets
# pulling out using column name this gives as pandas Series.
my_df2["Organization"]

0                             Google
1                             Google
2                             Google
3                                IBM
4                             Google
                   ...
618                     Google Cloud
619                      Campus BBVA
620          University of Minnesota
621    University of Colorado System
622                          Infosec
Name: Organization, Length: 623, dtype: object

In [27]:
#select specific column using dot notation
# pulling out using column name this gives as pandas Series.
my_df2.Organization

0                             Google
1                             Google
2                             Google
3                                IBM
4                             Google
                   ...
618                     Google Cloud
619                      Campus BBVA
620          University of Minnesota
621    University of Colorado System
622                          Infosec
Name: Organization, Length: 623, dtype: object

In [29]:
#select specific column using location
my_df2.iloc[:,0]

0        0
1        1
2        3
3        4
4        5
      ...
618    624
619    625
620    626
621    627
622    628
Name: Unnamed: 0, Length: 623, dtype: int64